### ISSUE TITLE
Feature: Reimplement missing worldgen features and decorations that have temporarily been disabled.

### ISSUE THREAD

**Issue by bconlon1** [Gilded-Games/The-Aether#499]
- [ ] Holiday Tree (see: #334)
- [x] Grass Patch (see: #330)
- [x] Tall Grass Patch (see: #330)
- [x] Lake
- [x] Spring (Waterfall)
